# Generated by Django 4.1.5 on 2023-02-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_id",
                    models.CharField(max_length=200, verbose_name="ID компании"),
                ),
                (
                    "amount_db",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Количество денег"
                    ),
                ),
                ("local_id", models.UUIDField(verbose_name="локальный айдишник")),
                (
                    "requisite_db",
                    models.CharField(max_length=200, verbose_name="Реквизиты"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (2, "Принят"),
                            (3, "В ожидании"),
                            (4, "Обрабатывается"),
                            (5, "Проведен"),
                            (6, "Неудача"),
                            (7, "Отменен"),
                            (8, "Принудительно отменен"),
                            (9, "Неудача при отмене"),
                            (10, "Частичная отмена"),
                        ],
                        max_length=100,
                        verbose_name="Статусы",
                    ),
                ),
            ],
        ),
    ]
