# Generated by Django 4.1.5 on 2023-02-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paysys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paysyshistory",
            name="add_balance",
            field=models.BooleanField(default=False),
        ),
    ]
