# Generated by Django 4.1.5 on 2023-03-09 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("kassa_services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requisite",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Реквизиты"
                    ),
                ),
                (
                    "amount",
                    models.CharField(max_length=11, verbose_name="Количество денег"),
                ),
                ("user", models.IntegerField(verbose_name="User ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (2, "Принят"),
                            (3, "В ожидании"),
                            (4, "Обрабатывается"),
                            (5, "Проведен"),
                            (6, "Неудача"),
                            (7, "Отменен"),
                            (8, "Принудительно отменен"),
                            (9, "Неудача при отмене"),
                            (10, "Частичная отмена"),
                        ],
                        default=3,
                        max_length=100,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="DateTime requests "
                    ),
                ),
                (
                    "integration",
                    models.CharField(
                        choices=[("kassa24", "kassa24"), ("paysys", "paysys")],
                        max_length=50,
                        verbose_name="Integration use",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Service name",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("uzs", "uzs"),
                            ("usd", "usd"),
                            ("eur", "eur"),
                            ("rub", "rub"),
                        ],
                        max_length=5,
                        null=True,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "client_ip_addr",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "payment_id",
                    models.IntegerField(
                        null=True, verbose_name="payment id transaction"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        max_length=100, verbose_name="ID transaction result"
                    ),
                ),
                (
                    "mx_id",
                    models.CharField(
                        max_length=100, null=True, verbose_name="MX_ID response"
                    ),
                ),
                (
                    "confirm_url",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="confirm url",
                    ),
                ),
                (
                    "error",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="error response",
                    ),
                ),
                (
                    "pay_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="pay id"
                    ),
                ),
                (
                    "service_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="payment",
                        to="kassa_services.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "partner_id",
                    models.UUIDField(verbose_name="partner_trans_id or local_id"),
                ),
                (
                    "add_balance",
                    models.BooleanField(default=False, verbose_name="add balance"),
                ),
                (
                    "payment_db",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction",
                        to="payment.payment",
                    ),
                ),
            ],
        ),
    ]
