# Generated by Django 4.1.5 on 2023-03-09 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaysysCancel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "error",
                    models.CharField(
                        blank=True,
                        help_text="Не заполняйте это поле ^",
                        max_length=100,
                        null=True,
                        verbose_name="cancel error",
                    ),
                ),
                ("done", models.BooleanField(default=False)),
                (
                    "transaction",
                    models.ForeignKey(
                        help_text="Выберите транзакцию по которой произойдет отмена платежа",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancel",
                        to="payment.transaction",
                    ),
                ),
            ],
        ),
    ]
